- hosts: localhost
  become: true
  vars_files:
    - inventory/group_vars/all.yml
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
    - name: upgrade apt
      apt:
        upgrade: dist

  tasks:
    - include: tasks/packages.yml
    - include: tasks/aws.yml
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/dev.yml

