- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
    - name: upgrade apt
      apt: upgrade: dist

  tasks:
    - include: tasks/packages.yml

