- name: Clone git-secrets
  git:
    repo: https://github.com/awslabs/git-secrets.git
    dest: work/git-secrets
  become: yes
  become_user: root
- name: Install git-secrets
  shell:
    cmd: make install
    chdir: work/git-secrets
  become: yes
  become_user: root


