- name: Clone bash-it
  git:
    repo: https://github.com/Bash-it/bash-it.git
    dest: /home/{{username}}/.bash_it
    depth: 1
- name: Install bash-it
  shell:
    cmd: sudo -u {{username}} /home/{{username}}/.bash_it/install.sh > bash_it.out 2>&1
    chdir: /home/{{username}}

