- name: Clone bash-it
  git:
    repo: https://github.com/Bash-it/bash-it.git
    dest: /home/{{username}}/.bash_it
    depth: 1
  become: yes
  become_user: "{{username}}"
- name: Install bash-it
  shell:
    cmd: /home/{{username}}/.bash_it/install.sh > bash_it.out 2>&1
    chdir: /home/{{username}}
  become: yes
  become_user: "{{username}}"
- name: create working directory
  file:
    path: work
    state: directory
    owner: ansible

    

