- name: create ansible user
  user: name=ansible uid=900
- name: create mortal user
  user:
    name: "{{username}}"
    groups: adm,sambashare,plugdev,cdrom,sudo,lpadmin
    shell: /usr/bin/bash
- name: copy ansible sudoers template file
  template:
    src: templates/sudoer.j2
    dest: /etc/sudoers.d/ansible
    mode: 0440
    validate: /usr/sbin/visudo -cf %s
  vars:
    username: ansible
  become: yes
  become_user: root
- name: copy user sudoers template file
  template:
    src: templates/sudoer.j2
    dest: /etc/sudoers.d/{{username}}
    mode: 0440
    validate: /usr/sbin/visudo -cf %s
  become: yes
  become_user: root
- name: copy variable test  template file
  template:
    src: templates/test.j2
    dest: /tmp/test.txt
    mode: 0666
